### ISSUE TITLE
open-in-browser pops up when going to ting.com

### ISSUE THREAD

**Issue by LinAGKar** [Rob--W/open-in-browser#71] opened 2021-02-22 12:54 UTC
If you try to go https://ting.com/ with this installed, the open-in-browser-dialog pops up, and you have to click OK (with open in Firefox or open as server sent MIME selected), to make the page load correctly.

**Comment by Rob--W** [comment] 2021-02-22 20:11
Duplicate of #61 (similar to #31 and #67).

As a work-around:

> This site does not send any `Content-Type` header. For a work-around, see https://github.com/Rob--W/open-in-browser/issues/61#issuecomment-535392064

**Closed by Rob--W** 2021-02-22 20:11 UTC
