### ISSUE TITLE
Download popup after closing page

### ISSUE THREAD

**Issue by rennex** [Rob--W/open-in-browser#20] opened 2017-11-19 10:11 UTC
Hi, I've gotten a download popup from a page that I had already closed. I've repeated it a couple of times today, and I also got it from some other site once before (I ignored it then).

This link does it reliably at least currently: [https://www.avk.fi/ajoneuvot/audi/a6/590736/audi-a6-3-0tdi-quattro](https://www.avk.fi/ajoneuvot/audi/a6/590736/audi-a6-3-0tdi-quattro)

After closing the tab, about 4-5 minutes later this popped up:

<img width="365" alt="avkpic" src="https://user-images.githubusercontent.com/449856/32989523-8cb1b2f6-cd20-11e7-8113-fe1fdb69fa1f.png">

I don't know if it's necessarily this extension's doing, but I think if it was in vanilla Firefox, it would've been caught already. One thought I had is that maybe the site might have some web worker that stays running and does some caching stuff or something, is that possible these days?

Another extension that I have that might be interested in closed tabs is Dustman, but I haven't set any 5-minute timeout in it...

**Comment by rennex** [comment] 2017-11-19 10:23
The URL it points to is [https://www.avk.fi/Shop/File/Show/94da32ea-51b3-42fc-9cd0-309ff5bc63da?t=2](url). Choosing "Open in browser" seems to do nothing with it, when it's a spurious popup.

Testing some more, I also got the popup only about 1.5 minutes after closing the page. And at least twice now, opening the url of the image itself has caused two popups to appear. Selecting "Open in browser" in the top one (latter) did nothing, and selecting it again in the first one showed it as a picture like it should.

**Comment by rennex** [comment] 2017-11-19 10:39
And one more piece of info, in case it helps: I noticed the image is served with a `Content-Type: image/JPG` header. Naughty and non-standard...

**Comment by Rob--W** [comment] 2017-11-19 10:47
Could you paste all response headers? I am mainly interested in
`Content-Disposition`.

image/JPG should not have triggered a download.

**Comment by rennex** [comment] 2017-11-19 13:08
Sure, here are the headers I get with curl:

```
$ curl -I -X GET https://www.avk.fi/Shop/File/Show/94da32ea-51b3-42fc-9cd0-309ff5bc63da?t=2
HTTP/1.1 200 OK
Cache-Control: public, max-age=469
Content-Type: image/JPG
Expires: Sun, 19 Nov 2017 13:15:42 GMT
Last-Modified: Sun, 19 Nov 2017 13:05:42 GMT
Vary: *
Server: Microsoft-IIS/8.5
X-Generator: Orchard
X-AspNetMvc-Version: 5.2
Content-Disposition: attachment; filename=94da32ea-51b3-42fc-9cd0-309ff5bc63da.JPG
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
X-Host: 1
Date: Sun, 19 Nov 2017 13:07:53 GMT
Content-Length: 31919
```

**Comment by Rob--W** [comment] 2017-11-19 15:56
This is odd. I can confirm that after closing the tab, that requests are generated (Firefox Nightly 59.0a1 buildID 20171116220410). I have monitored and debugged Firefox for almost two hours, and found that something is sending a request every 5 minutes. The fact that my extension shows a dialog is a just a symptom, the <s>root cause still unknown</s>.
These requests appear to be initiated by Firefox's thumbnail generation component.

I tried many different methods, but what ultimately helped with finding the root cause is to start the Gecko Profiler right before the expected request was scheduled, and then open and read the generated profile. In the profiles I found references to "backgroundPageThumbs", which looked like a plausible source of unexpected requests:

- https://perfht.ml/2zRI2th (reference to [backgroundPageThumbsContent.js](https://searchfox.org/mozilla-central/rev/c9214daa09e3eb8246b1448e469df1652a140825/toolkit/components/thumbnails/content/backgroundPageThumbsContent.js)).
- https://perfht.ml/2zTETZE (confirmed again - reference to [backgroundPageThumbsContent.js](https://searchfox.org/mozilla-central/rev/c9214daa09e3eb8246b1448e469df1652a140825/toolkit/components/thumbnails/BackgroundPageThumbs.jsm))

And indeed, I found a 5 minute interval at https://searchfox.org/mozilla-central/rev/c9214daa09e3eb8246b1448e469df1652a140825/toolkit/components/thumbnails/BackgroundPageThumbs.jsm#9

Now that I know the root cause of the issue, I guess that it is somewhat safe to ignore these requests in the extension by ignoring requests with `tabId` -1 (based on the below information).


Here are two of them (logged the value of "request") in background.js, after returning from the dialog.

```
{
    "requestId": "242",
    "url": "https://www.avk.fi/Shop/File/Show/94da32ea-51b3-42fc-9cd0-309ff5bc63da?t=2",
    "originUrl": null,
    "documentUrl": undefined,
    "method": "GET",
    "type": "main_frame",
    "timeStamp": 1511099632540,
    "frameId": 0,
    "parentFrameId": -1,
    "fromCache": false,
    "responseHeaders": [
        {
            "name": "Cache-Control",
            "value": "public, max-age=300"
        },
        {
            "name": "Content-Type",
            "value": "image/JPG"
        },
        {
            "name": "Expires",
            "value": "Sun, 19 Nov 2017 13:58:53 GMT"
        },
        {
            "name": "Last-Modified",
            "value": "Sun, 19 Nov 2017 13:48:53 GMT"
        },
        {
            "name": "Vary",
            "value": "*"
        },
        {
            "name": "Server",
            "value": "Microsoft-IIS/8.5"
        },
        {
            "name": "X-Generator",
            "value": "Orchard"
        },
        {
            "name": "X-AspNetMvc-Version",
            "value": "5.2"
        },
        {
            "name": "Content-Disposition",
            "value": "attachment; filename=94da32ea-51b3-42fc-9cd0-309ff5bc63da.JPG"
        },
        {
            "name": "X-AspNet-Version",
            "value": "4.0.30319"
        },
        {
            "name": "X-Powered-By",
            "value": "ASP.NET"
        },
        {
            "name": "X-Host",
            "value": "2"
        },
        {
            "name": "Date",
            "value": "Sun, 19 Nov 2017 13:53:52 GMT"
        },
        {
            "name": "Content-Length",
            "value": "31919"
        }
    ],
    "statusCode": 200,
    "statusLine": "HTTP/1.1 200 OK",
    "proxyInfo": null,
    "ip": "77.86.239.249",
    "frameAncestors": [],
    "tabId": -1
}
```

```
{
    "requestId": "247",
    "url": "https://www.avk.fi/Shop/File/Show/94da32ea-51b3-42fc-9cd0-309ff5bc63da?t=2",
    "originUrl": null,
    "documentUrl": null,
    "method": "GET",
    "type": "main_frame",
    "timeStamp": 1511099932551,
    "frameId": 0,
    "parentFrameId": -1,
    "fromCache": false,
    "responseHeaders": [
        {
            "name": "Cache-Control",
            "value": "public, max-age=0"
        },
        {
            "name": "Content-Type",
            "value": "image/JPG"
        },
        {
            "name": "Expires",
            "value": "Sun, 19 Nov 2017 13:58:53 GMT"
        },
        {
            "name": "Last-Modified",
            "value": "Sun, 19 Nov 2017 13:48:53 GMT"
        },
        {
            "name": "Vary",
            "value": "*"
        },
        {
            "name": "Server",
            "value": "Microsoft-IIS/8.5"
        },
        {
            "name": "X-Generator",
            "value": "Orchard"
        },
        {
            "name": "X-AspNetMvc-Version",
            "value": "5.2"
        },
        {
            "name": "Content-Disposition",
            "value": "attachment; filename=94da32ea-51b3-42fc-9cd0-309ff5bc63da.JPG"
        },
        {
            "name": "X-AspNet-Version",
            "value": "4.0.30319"
        },
        {
            "name": "X-Powered-By",
            "value": "ASP.NET"
        },
        {
            "name": "X-Host",
            "value": "2"
        },
        {
            "name": "Date",
            "value": "Sun, 19 Nov 2017 13:58:52 GMT"
        },
        {
            "name": "Content-Length",
            "value": "31919"
        }
    ],
    "statusCode": 200,
    "statusLine": "HTTP/1.1 200 OK",
    "proxyInfo": null,
    "ip": "77.86.239.249",
    "frameAncestors": [],
    "tabId": -1
}
```

I attached a debugger to the browser, and found that is a response to a request for the same URL, but then the HTTP version of the URL. The HTTP version 302-redirects to HTTPS.
In order to determine the source of the request, I tried to peek in the channel (Firefox internals).

```
channel.loadFlags = 40452804
bits from nsIRequest
 2 LOAD_DOCUMENT_NEEDS_COOKIE
 6 INHIBIT_PIPELINE -- ???? Gone from nsIRequest.idl in bug 1344374
 7 INHIBIT_CACHING
 9 LOAD_BYPASS_CACHE 
14 LOAD_ANONYMOUS
bits from nsIChannel.idl
16 LOAD_DOCUMENT_URI
19 LOAD_INITIAL_DOCUMENT_URI
21 LOAD_CALL_CONTENT_SNIFFERS
22 LOAD_CLASSIFY_URI
25 LOAD_BYPASS_SERVICE_WORKER
```

The presence of bit 6 suggests that maybe all bits are initially set (`LOAD_REQUESTMASK`), and then some are explicitly zeroed ([nsIRequest.idl](https://searchfox.org/mozilla-central/rev/c9214daa09e3eb8246b1448e469df1652a140825/netwerk/base/nsIRequest.idl) defines the first 15 bits, [nsIChannel.idl](https://searchfox.org/mozilla-central/rev/c9214daa09e3eb8246b1448e469df1652a140825/netwerk/base/nsIChannel.idl) the others).

**Comment by Rob--W** [comment] 2017-11-19 16:04
To disable this thumbnail feature of Firefox:

1. Visit `about:config`
2. Create a new Boolean preference, set `browser.pagethumbnails.capturing_disabled` to `true`.

**Comment by rennex** [comment] 2017-11-21 08:48
Well this turned out to be difficult. Thanks for all the effort fixing this! When I had done a bit more testing, the dialogs haunted me for a long time, laying in wait for 45 minutes or more, and then popping up when I resumed using the browser. Hopefully this update will stop them for good :)

**Closed** 2017-11-21 10:47 UTC
