### ISSUE TITLE
Dialog resizing slightly off with HiDPI Display

### ISSUE THREAD

**Issue by Dani21** [Rob--W/open-in-browser#29] opened 2017-12-13 22:00 UTC
On my hi-res laptop (3000x2000 at 200% scaling), I see a scrollbar with the download prompt. I can also resize the prompt (which lets me temporarily fix it I guess). I have the latest version of this extension installed (2.5) and the most up-to-date version of Firefox (57.0.2). Here's a screenshot:

![dialog prompt screenshot](https://user-images.githubusercontent.com/1804643/33964500-8690dfc8-e00d-11e7-866f-0bee12690d9f.png)

Btw thanks for keeping up the development after FF57 hit! I disabled the extension after upgrading and testing it today I've been pleasantly surprised with how good it's gotten again 👍

**Comment by Rob--W** [comment] 2017-12-15 17:50
When you press F12 and F12 again (open devtools and close it), do you still see the scrolbar?

I saw this issue before, and it is caused by a small difference of calculating the dialog size. The calculated size ought to be sufficient, but when rendered the browser first tried to render the content with scrollbar even though it is not necessary.

If my suggested work-around (F12 F12) fixes the issue, then I will submit a patch to try and render without scrollbar, initially.

**Comment by Lekensteyn** [comment] 2017-12-27 13:01
The same scrollbar issue occurs when a long filename wraps over the next line.

Try to download "0001-Avoid-redirecting-output-to-file-when-tcgetpgrp-fail.patch" from https://savannah.gnu.org/bugs/?51181 for example. F12 F12 solves the issue here, the dialog does not resize but the scrollbar is gone.

**Comment by Rob--W** [comment] 2017-12-27 16:52
I have fixed the bug as reported by @Lekensteyn .

I have been experimenting with pixel density of more than 1 per pixel (via `layout.css.devPixelsPerPx = 2` at `about:config`) and the results look inconclusive.

@Dani21 Could you check whether my previous suggestion (https://github.com/Rob--W/open-in-browser/issues/29#issuecomment-352069284) fixes the issue for you? If so then my submitted patch will also fix the issue for you. If not, then more debugging is necessary.

**Closed** 2018-06-03 14:38 UTC
